require("prototypes.item.item-groups")
require("prototypes.item.AdvancedEquipment")
require("prototypes.recipe.AdvancedEquipment")
require("prototypes.technology.AdvancedEquipment")
require("prototypes.equipment.AdvancedEquipment")
require("prototypes.AdvancedEquipmentGUI")